name: pandt
version: 0.1.0.0
synopsis: Phone-and-Tablet Roleplaying Game
maintainer: radix@twistedmatrix.com
license: MIT
github: radix/pandt
category: Game Engine
ghc-options: -threaded -rtsopts -with-rtsopts=-N

default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings
    - GADTs
    - MultiWayIf
    - LambdaCase
    - QuasiQuotes
    - RecordWildCards

dependencies:
    - base-noprelude
    - classy-prelude
    - containers
    - grid
    - interpolate
    - lens
    - mtl
    - template-haskell
    - text
    - transformers

library:
    source-dirs: src
    ghc-options: -Wall -Werror

executables:
    pandt-cli:
        main: Main.hs
        source-dirs:
            - app
        dependencies:
            - pandt

tests:
    spec:
        main: Spec.hs
        source-dirs:
            - test
        
