single_line_if_else_max_width = 100
max_width = 100
tab_spaces = 2
fn_args_density = "Compressed"
chain_one_line_max = 100
fn_call_width = 100
struct_lit_width = 100
struct_variant_width = 100

write_mode = "Overwrite"
