[package]
name = "ptrpi"
version = "0.1.0"
authors = ["Christopher Armstrong"]

[dependencies]
actix = "0.5"
actix-web = "0.4"
env_logger = "0.5"
error-chain = "0.11.0-rc.2"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
foldertree = {version = "*", path = "../foldertree"}
http = "0.1"
hyper = "~0.11.7"
log = "0.3"
pandt = {version = "*", path = "../pandt"}
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
serde_yaml = "0.7.0"
structopt = "0.2"
tokio-core = "0.1"
