[package]
name = "ptrpi"
version = "0.1.0"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
serde_yaml = "0.5.1"
futures = "0.1.8"
unicase = "1.4.0"

[dependencies.pandt]
path = "../pandt"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
