[package]
name = "ptrpi"
version = "0.1.0"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]

[dependencies]
log = "0.3"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
serde_yaml = "0.7.0"
error-chain = "0.11.0-rc.2"
failure = "0.1"
failure_derive = "0.1"
hyper = "~0.11.7"
mime = "0.3"
multiqueue = "0.3"
futures = "0.1"

[dependencies.pandt]
path = "../pandt"

[dependencies.gotham]
rev = "1e4c7027b2a76dca7d96be64e33532db1ecd76ce"
git = "https://github.com/gotham-rs/gotham"

[dependencies.gotham_derive]
rev = "1e4c7027b2a76dca7d96be64e33532db1ecd76ce"
git = "https://github.com/gotham-rs/gotham"
