[package]
name = "ptrpi"
version = "0.1.0"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]

[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
serde_yaml = "0.6"
unicase = "1.4.0"
rocket = "0.2"
rocket_codegen = "0.2"
rocket_contrib = "0.2"
bus = "1.1.3"

[dependencies.pandt]
path = "../pandt"

