[package]
name = "ptrpi"
version = "0.1.0"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]

[dependencies]
# actix = "0.4.5"
env_logger = "0.5"
error-chain = "0.11.0-rc.2"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
http = "0.1"
hyper = "~0.11.7"
log = "0.3"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
serde_yaml = "0.7.0"
tokio-core = "0.1"

[dependencies.pandt]
path = "../pandt"

[dependencies.actix]
git = "https://github.com/actix/actix.git"
# rev = "cd3ff610d9acd64b49d865d257c193862058a59c"

[dependencies.actix-web]
git = "https://github.com/actix/actix-web"
rev = "d0cbf7cd2538bedc2aff34967235c3dfe6396430"
