[package]
name = "ptrpi"
version = "0.1.0"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]

[dependencies]
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
serde_yaml = "0.7.0"
rocket = {git = "https://github.com/SergioBenitez/Rocket/", rev = "923b84f42c9a96e2e012cec7cad50b327c255717"}
rocket_codegen = {git = "https://github.com/SergioBenitez/Rocket/", rev = "923b84f42c9a96e2e012cec7cad50b327c255717"}
rocket_contrib = {git = "https://github.com/SergioBenitez/Rocket/", rev = "923b84f42c9a96e2e012cec7cad50b327c255717"}
bus = "1.2.0"
error-chain = "0.10.0"

[dependencies.pandt]
path = "../pandt"

