[package]
name = "ptrpi"
version = "0.1.0"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]

[dependencies]
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
serde_yaml = "0.7.0"
rocket = "0.3.0"
rocket_codegen = "0.3.0"
rocket_contrib = "0.3.0"
bus = "1.2.0"
error-chain = "0.10.0"

[dependencies.pandt]
path = "../pandt"

