[package]
name = "foldertree"
version = "0.1.0"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
serde = {version = "1.0", optional = true, features = ["derive"]}

[dev-dependencies]
serde_json = "1.0"
