[package]
name = "pandt"
version = "0.1.0"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]

[dev-dependencies]
serde_json = "1.0.2"

[dependencies]
bresenham = "0.1.1"
derive_more = "0.4.0"
error-chain = "0.11.0-rc.2"
failure = "0.1"
failure_derive = "0.1"
log = "0.3"
maplit = "0.1.4"
nalgebra = "0.11.2"
ncollide = "0.11.0"
nonempty = {version = "*", path = "../nonempty", features = ["use_serde"]}
num = "0.1.41"
num-traits = "0.1.41"
odds = "0.2.25"
rand = "0.3"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_yaml = "0.7.0"
uuid = {version = "0.5", features = ["v4", "serde"]}

[dependencies.uom]
# version = "0.16"
git = "https://github.com/iliekturtles/uom"
rev = "e10f7ecf31ecc9c49f9909419566629892cd4dfc"
features = ["u8", "i8", "u16", "i16", "u32", "i32", "u64", "i64", "f32", "f64", "serde"]
