[package]
name = "pandt"
version = "0.1.0"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]

[dev-dependencies]
serde_json = "1.0.2"

[dependencies]
serde = "1.0.8"
serde_derive = "1.0.8"
nonempty = {version = "*", path = "../nonempty", features = ["use_serde"]}
serde_yaml = "0.7.0"
odds = "0.2.25"
nalgebra = "0.11.2"
ncollide = "0.11.0"
derive_more = "0.4.0"
string-wrapper = {version = "0.3", features = ["use_serde"]}
num-traits = "0.1.36"
rand = "0.3"
uuid = {version = "0.5", features = ["v4", "serde"]}
error-chain = "0.11.0-rc.2"
bresenham = "0.1.1"
maplit = "0.1.4"
